### ISSUE TITLE
openambit doesn't sync with movescount

### ISSUE THREAD

**Issue by mklopotnuk** [openambitproject/openambit#253] opened 2020-06-28 18:07 UTC
Hello! I've updated Qt few days ago - from 5.14.2-3 to 5.15.0. Perhaps after that openambit doesn't sync with movescount. Error:
Failed to upload log (err code: QNetworkReply::ProtocolInvalidOperationError ), movescount.com replied with " "" "

OS Archlinux, Openambit-cli 0.5

**Comment by mklopotnuk** [comment] 2020-07-06 14:06
Today i've downgraded qt and icu. Now openambit can sync with movescount. But now i cant upgrade qt.

**Comment by centic9** [comment] 2020-07-07 19:59
Which distribution are you using for getting this version of Qt?

Debian/Ubuntu does not seem to have it available yet in the latest unstable versions.

**Comment by mklopotnuk** [comment] 2020-07-08 02:11
I've wrote that in first message:
"OS Archlinux, Openambit-cli 0.5"

**Comment by centic9** [comment] 2020-07-09 15:35
This is a regression in QT 5.15, see item 2.) in https://bugreports.qt.io/browse/QTBUG-85264

There is no some "auto-conversion to base64 happening which means Openambit actually encodes the data twice now due to this.

**Comment by zander** [comment] 2020-07-09 16:28
check https://bugreports.qt.io/browse/QTBUG-84739

which is open P1 (meaning its a showstopper for 5.15.1)

**Comment by miir01** [comment] 2020-07-22 12:06
Hi,

I get this error: Upload error: "Invalid CompressedValues: Invalid length for a Base-64 char array or string."
Is this what you are talking about? Will there be a solution for that?

**Comment by centic9** [comment] 2020-07-28 19:39
Hopefully it will be fixed in the next bugfix version of Qt, the issue is still set to revert to the previous behavior in Qt 5.15.1.

**Comment by PrzemekRychter** [comment] 2020-09-03 21:27
Hi, i followed readme in order to install openAmbit and synch with movescount, but it doesn't work (It is not syncing but openAmbit see the watch and sync, but i cannot sync with site)
I tried to change qt version but i dont know how exacly.
```
$ qmake --version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
```
How do I change 5.12.8 to other ?

**Comment by strawpants** [comment] 2020-09-14 07:19
Hi all,
I faced the same issue on a Arch linux installation with qt 5.15.0, but I can confirm the movescount sync works again with qt version 5.15.1-1 (which just arrived in the Arch repositories).

So the moral of the story is indeed: don't install qt 5.15.0 (downgrade or wait for 5.15.1)

**Comment by centic9** [comment] 2021-02-19 21:01
So I think we can close this one as it was fixed in Qt itself since some time now. 

Please note that movescount recently stopped accepting connections with the current "APPKEY", see the discussion at #216, there seems to be some way to continue to use it, but it is not yet fully analysed yet.

**Closed by centic9** 2021-02-19 21:01 UTC
Labels: qt5, wontfix
