### ISSUE TITLE
Add support for Ambit 3

### ISSUE THREAD

**Issue by svenstorp** [openambitproject/openambit#54] opened 2014-09-05 18:13 UTC
- Add device ID to libambit, and udev rules
- Investigate communication protocol

**Comment by mephistopheles78** [comment] 2015-05-10 13:49
Unfortunately, sync still does not work with Ambit 3 Peak:
````INFO: ambit_device_info_new(): HID  : /dev/hidraw0: 'Suunto Ambit' (serial: 9820105115001800, VID/PID: 1493/001b)
libambit INFO: device_info_get(): Reading device info
libambit INFO: ambit_device_info_new(): preferring known name over HID 'Suunto Ambit'
libambit INFO: ambit_device_info_new(): Ambit: /dev/hidraw0: 'Suunto Ambit3 Peak' (serial: 9820105115001800, VID/PID: 1493/001b, nick: Emu, F/W: 1.5.44, H/W: 69.2.17410, supported: YES)
libambit INFO: libambit_device_driver_status_get(): Reading device status
libambit INFO: libambit_device_driver_status_get(): Reading device status
libambit INFO: libambit_device_driver_status_get(): Reading device status
libambit INFO: personal_settings_get(): Reading personal settings
libambit INFO: log_read(): Reading log headers
libambit WARNING: get_memory_maps(): Failed to read memory map key````

**Comment by pdizzle** [comment] 2015-06-20 01:45
Hey there,

I am looking into getting an ambit3, is this still in a testing phase or is it considered fully/mostly functional? I only have a linux machine but I'd be willing to provide what I can if needed.

**Comment by sojkin** [comment] 2015-08-27 20:11
Hello

any news when Ambit 3 will be implemented?  

regards 
Marcin

**Comment by mbernasocchi** [comment] 2015-08-28 09:21
it is already

**Comment by sojkin** [comment] 2015-08-30 08:44
![zrzut ekranu z 2015-08-30 10 42 15](https://cloud.githubusercontent.com/assets/2184760/9566392/f52eb664-4f03-11e5-8834-cf36ce39d56b.png)

when I'm connecting my Ambit 3 I get message that it's not supported yet.

**Comment by marguslt** [comment] 2015-08-31 15:35
0.3 was released on 16 Sep 2014, you might want to try something more up to date and build from source. It's actually quite straightforward.

**Comment by mephistopheles78** [comment] 2015-09-01 12:57
I'm still facing problems with using openambit and my Ambit3 Peak:
![suunto_ambit3_peak](https://cloud.githubusercontent.com/assets/12381495/9604702/68f4bd08-50b9-11e5-97a4-2928e0ae675d.png)

Debugging information:
```
libambit INFO: personal_settings_get(): Reading personal settings
libambit INFO: libambit_device_driver_date_time_set(): Writing date and time to clock
libambit INFO: log_read(): Reading log headers
libambit WARNING: get_memory_maps(): Failed to read memory map key
libambit INFO: libambit_close(): Closing
```

**Comment by tambit** [comment] 2015-09-15 18:58
I just received my Ambit 3 Peak running fw rev 2.0.4 and at first glance I am seeing the same problem as  mephistopheles78 when running latest openambit-master. After spending some time with wireshark I found 

- Get settings
- Set Date
- Set Time
- Get Device Info

seem to work flawless. Where I see problem is actually "Get Lock Status" and "Get Log Header". Regarding "Get Lock Status" I already spent some more time and have some questions to get a better understanding of the protocol:

1. what could it mean if the watch replies to GetLockStatus with a message having packet length 0?
2. when sending command 0x0b190500 I found in another persons log the reply 0x0b190a00. When looking at my log I get 0x0b190202 back from the watch. In my understanding so far byte 0&1  are the actual command , byte2=05 means send, byte2=0a receive, but what is the meaning of byte2=02?

**Comment by paddy-hack** [comment] 2015-09-16 11:24
I have been looking at the details of the protocol (using a "regular" Ambit) a bit over the summer with the intent of producing some documentation.  From my observations the `0202` part of what you see very likely means "command not supported".  So the 0 length reply payloads are understandable.  IIRC from my Ambit, failure to "Get Lock Status" is not necessarily problematic.  If that is the case for your Ambit3 Peak, then the "Get Log Header" may be where the real problem is.

I am rather busy with a different project at the moment, but I am very interested in your captures to see how they match my notes.  Captures using MovesLink would be even better.  When running MovesLink in a VM you can use `wireshark` to do the capture.

**Comment by nh2** [comment] 2015-12-20 15:00
Would it help if we set aside a computer connected to the Ambit 3 which you could SSH into?

**Comment by tambit** [comment] 2016-01-07 20:06
I have actually working code for fw versions > 2 (2.0.4 & 2.0.45). Although it works for me, it still needs some further testing and the biggest problem I currently see is how to handle compatibility with previous firmware versions.

Please let me know your thoughts on backward compatibility.

**Comment by paddy-hack** [comment] 2016-01-08 10:59
Being able to look at and try out your working code would be immensely helpful.  Could you push it to your openambit clone?  Then the adventurous Ambit3 owners can test your code and everyone can chime in on your backward compatibility concerns.

**Comment by tambit** [comment] 2016-01-08 12:10
Ok I just pushed it as you suggested. Currently the code is setup to work with 2.0.45, but it should also work on 2.0.4 when komposti_version in libambit.c is adjusted accordingly. I am not 100% sure if this is really required, but probably somebody still running on 2.0.4 can comment on this.

Syncing FW versions <2 will definitely fail in the current state of the code. The wireshark dissector should work for all.

All the adventurous people out there - have fun testing!

**Comment by Idiotein** [comment] 2016-01-27 15:04
I can report success with tambit code, built on Debian amd64 Sid. My Ambit3 Peak "Emu" running logs sync properly. The watch is running on the latest firmware (2.0.45).

Big thank you to tambit for this !

**Comment by rideyourstyle** [comment] 2016-03-11 15:19
Today, i checked out the actual source and tested openambit with Ambit3 Peak (2.0.24). The watch was successful detected but sync failed.
where are the log files located? Can i help with my logfile?

**Comment by Idiotein** [comment] 2016-03-12 11:16
Hello rideyourstyle,

I assume you are talking about tambit code preview.
As tambit said his code works only with last firmware version (maybe 2.0.4 too) and breaks compatibility for older ones, so there isn't an option right now around upgrading the firmware first.
My watch is running on 2.0.45 and tambit openambit code works mostly well for running/trail logs, except for minimal heart rate which seems to always be "0", no big deal for me.

**Comment by bubulle** [comment] 2016-03-13 06:59
Hello folks,

Are there plans to merge tambit's code at some point ? As the Debian package maintainer, I'd really love having in Debian Stretch a version that supports Ambit 3 watches (even though I'm a happy owner of Ambit 2 nowadays). I understand it only works with Ambit 3 latest firmware but does it introduce regressions for Ambit 2 owners ?

To tambit: where could I get my hands on your code (simple git command lines would help as I'm not a git wizard) so that I can try building a package from it, for Debian experimental ?

**Comment by Idiotein** [comment] 2016-03-13 10:05
Hello bubulle,

nice to see you interested in this issue, and big thank you for your work in Debian!

Right now I am in a strange situation with my Ambit2, it doesn't work on my Debian stable + backport computers with neither regular openambit or Tambit code. Sync fails toward the end (writing satellite data) and goes in a loop. I didn't have time to debug it yet, will do soon.
On my Sid system it works fine with Tambit code, I just double checked by making a short indoor move and synced without issue.
So barring my (possibly local) issue on stable, it works for me on Sid with both Ambit2 and 3.

I pulled the code from there : 
https://github.com/tambit/openambit

All the best.

**Comment by rideyourstyle** [comment] 2016-03-18 16:16
I have to check which version (openambit/tambit) I checked out. I worte the wrong version number of my Ambit3. It is the actual one 2.0.45.

Where are the logfiles located to check the problems with my watch?

Thanks

**Comment by salvojimmy** [comment] 2016-03-22 20:30
Hello guys, I tried to create an AUR package with the new tambit code for arch linux, I basically failed. 
Can someone try, please? It will make happy a lot of arch linux users.

Thanks in advance

**Comment by jadahl** [comment] 2016-04-24 09:38
I reworked tambit's patch and made a pull request: https://github.com/openambitproject/openambit/pull/113 . I'd be good if anyone with an Ambit3 with an older or newer firmware than 2.0.4 (which is the one my device has) could test it, and if something fails, maybe even send me some logs of successful synchronizations.

**Comment by microwan** [comment] 2016-05-17 18:23
Hello Jadahl ,

I have an Ambit 3 Peak with firmware 2.0.45. 
i will provide to you some new synchronizations with Wireshark.

                   Best Regards

**Comment by gbeste** [comment] 2016-10-26 11:57
Hi!

Newbie here :) Does any version of openambit work with Ambit3 Peak FW 2.2.16? I cannot get mine to work neither with openambit, nor with tambit version...

**Comment by crmoore** [comment] 2016-11-04 11:09
Device ID and codename for "Ambit 3 Run":  0x001e Ibisbill.

Currently running FM 2.0.45 and appears to work with PR#113.

**Comment by Idiotein** [comment] 2016-11-04 12:50
Hi gbeste, I am in the same situation, Tambit and Jadhal versions used to work, but right now for my Ambit3 Peak with firmware 2.2.16 nothing works on my Debian.

**Comment by jadahl** [comment] 2016-11-04 13:04
@Idiotein did you try with the needed change reported in comment https://github.com/openambitproject/openambit/pull/113#r61484915 ? I haven't gotten around to updating the pull request with that change.

**Comment by Idiotein** [comment] 2016-11-05 12:55
Hi jadahl, I applied the fix by reverting the version check in "src/libambit/device_driver_ambit3.c" from ">=" to "<=", it compiles fine on my Debian Sid box, but the watch locks up with the "update in moveslink" message. Am I supposed to modify the sources any further ?
On my Debian 8 "stable" system I can't build libambit right now, even with c99, can't figure out why.
Will have time to investigate tomorrow.
Thanks for your work and interest.

**Comment by Idiotein** [comment] 2016-11-08 08:19
Hi @jadahl, I answered in the [pull request thread](https://github.com/openambitproject/openambit/pull/113) and added captures, openambit doesn't work on Debian Stable or Sid for me. Seems like last firmware upgrade broke compatibility. If anyone as a different experience please share your solution.

**Comment by bartko-s** [comment] 2016-12-24 18:25
+1

**Comment by ekkia** [comment] 2017-04-11 12:52
Any news for ambit3 support?

**Comment by myadzel** [comment] 2017-04-20 08:12
+1

**Comment by landas** [comment] 2017-04-20 12:21
I don't have an ambit3, but I could help out if someone with an ambit3 would like to use some time to help out.

For me the best way is:
- Raw USB-logs from tcpdump, using moveslink2 on a virtual box Windows.
- Proxy moveslink2 trough one of my servers. (this will expose your login and security id to me)
(I will give details if someone is interested)

If someone is interested, write here or mail me landas@gmail.com :)

**Comment by onedayfishsale** [comment] 2017-04-24 18:43
I could potentially assist with Ambit3 dumps, etc. Ambit3 Sport running 2.4.1, Moveslink2 on Windows 10 on VMware.

**Comment by landas** [comment] 2017-04-24 19:28
Nice. If we could start with a simple route sync it would be easy for me to compare ambit2 vs ambit3.

I would be happy if you could sync your ambit3 with the following map:
http://www.movescount.com/map?route=2355077

Here is a recipe (after you have pluged your watch to the computer and started vm ware)

**1) Find bus number for your ambit**
In Linux terminal:
```
$ lsusb
```

**2) Tell movescount to sync TestOA route to watch**
Be sure the route is not allready synced to watch.

**3) Start tcpdump logging**
In the Linux terminal:
```
sudo tcpdump -i usbmon1 -X > ambit3.usb.log
```
Replace 1 in usbmon1 with the bus number reported by `lsusb` for ambit 3.

**4) Sync watch in moveslink2**
In VM Ware, Windows, start moveslink2 and sync your watch with movescount.

**5) When sync is finished**
In Linux terminal:
Ctrl-c to send termination signal to tcp dump.

Now you should have a log file with the name ambit3.usb.log. Send it to me :)

**Example of part of a usb.log-file:**
```
...
19:46:14.841346 CONTROL COMPLETE from 1:70:0
	0x0000:  0c03 4100 6d00 6200 6900 7400            ..A.m.b.i.t.
19:46:14.841748 CONTROL SUBMIT to 1:70:0
19:46:14.842074 CONTROL COMPLETE from 1:70:0
	0x0000:  2203 3200 3900 4100 4500 3000 4100 3500  ".2.9.A.E.0.A.5.
	0x0010:  3100 3100 3200 3000 3000 3000 3500 3000  1.1.2.0.0.0.5.0.
	0x0020:  3000                                     0.
19:46:14.844863 INTERRUPT SUBMIT from 1:70:2
	0x0000:  3f18 5d10 0100 2fb8 0000 0100 0000 0000  ?.].../.........
	0x0010:  0400 0000 0204 5900 af4f 0000 0000 0000  ......Y..O......
	0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0030:  0000 0000 0000 0000 0000 0000 0000 0000  ................
19:46:14.845640 INTERRUPT COMPLETE to 1:70:2
19:46:14.847627 INTERRUPT COMPLETE to 1:70:2
	0x0000:  3f3e 5d36 0200 1ad9 0002 0200 0900 0000  ?>]6............
	0x0010:  3000 0000 436f 6c69 6272 6900 0000 0000  0...Colibri.....
	0x0020:  0000 0000 3239 4145 3041 3531 3132 3030  ....29AE0A511200
	0x0030:  3035 3030 0200 1000 4b03 014b 0106 7fe4  0500....K..K....
19:46:14.847750 INTERRUPT SUBMIT from 1:70:2
...
```
**To dump USB traffic on Linux, the usbmon module is needed**
On Ubuntu I think this is configured default to work.
https://technolinchpin.wordpress.com/2015/10/23/usb-bus-sniffers-for-linux-system/

**Comment by onedayfishsale** [comment] 2017-04-25 12:10
Thanks for the good instructions, @landas. I'm emailing you two links, one dump with nothing to sync, and one dump only syncing the TestOA route. For each I started tcpdump, connected the virtual USB device to my VM, let Moveslink2 sync, then disconnected and stopped the tcpdump.

If anyone else wants to look at the dumps, let me know. They do contain a bit of personally identifiable information, but I can email them directly.

**Comment by Idiotein** [comment] 2017-04-26 07:16
Hello @landas, maybe you are already aware of [this effort](https://github.com/openambitproject/openambit/pull/113) from @jadahl , if not it could be a good idea to share resources.
Thanks for the help.

**Comment by jadahl** [comment] 2017-04-26 07:32
FWIW, in the pull request linked by @Idiotein ambit 3 devices with firmwares up to a specific version kind of works (there seems to be less information sent over the cable compared to what I expect, such as HR samples) and I have started to add support for newer firmwares, but haven't managed to get anything worth another pull request yet. I don't have the Movescount XML logs however, and haven't checked if syncing to that service works, as I don't use it.

I have so far observed at least three different generations of Ambit3 firwmwares, where the protocol differs slightly compared to what firmware is used. I have so far attempted to keep multiple firmware generations working in the same code base, currently adding the third one I've seen, which seems to be the one used in recent firmware versions.

**Comment by landas** [comment] 2017-04-26 10:27
Hi,

I'm aware of the effort of @jadahl, and I know there is some effort in the fork network. I'm just getting my feet wet to se how the ambit3 protocol compare with the ambit2 protocol. I also need to learn how the log-sync is working on both ambit2 and ambit3.

I don't know if we at this time should prioritise for backward compatibility, at least for me if will be impossible.

I'm not even sure how to attack this issue :smile:

@jadahl, if you have something that is kind of working I would be happy to help out if you tell me what your code is missing or bugs it have.

@jadahl could you give me an status update on your code on following topics:
- Device detection
- Charge status
- Sync time/date
- Sync logs
- Orbital data update

**Comment by jadahl** [comment] 2017-04-26 12:35
> I don't know if we at this time should prioritise for backward compatibility, at least for me if will be impossible.

I can understand that, but the fact is that I don't have access to any Windows or Mac computers, so I have had no way to upgrade my firmware. Maybe using Movescount on Wine (which has been reported to start working it seems) I can upgrade.

Current status:
> Device detection
Sport and Peak devices are detected properly.
> Charge status
IIRC it works properly
> Sync time/date
Seems to be using the same method as ambit2, but haven't actually double checked that it works.
> Sync logs
This is where I've spent my effort mostly. On my version of the firmware, logs are synced properly, but seems to be missing HR samples. It's not that they can't be parsed, they are simply not part of the data transferred over the cable. I suspect there is some extra command required for this but I don't have logs of the same firmware.
> Orbital data update
I think this works the same as Ambit2. I haven't verified so is the case.

Other relevant parts:
The wireshark dissector tool has been updated to work on newer wireshark versions, but hasn't been updated to newer firmwares.

Settings synchronization has been mostly implemented. See pull 108. You can probably help with the issue the reviewer at the time raised.

Do you know if there is any

**Comment by landas** [comment] 2017-04-28 14:18
@onedayfishsale @Idiotein could you try to compile from this repository:
https://github.com/landas/openambit/tree/jadahl

It's the same code as pull request #113 :
+ Updated komposti version
+ Updated get_memory_maps for Firmware 2.4.1 (AMBIT_FW_GEN3)

Remember to compile with `-DCMAKE_BUILD_TYPE=Debug` (it gives more debug info in console)

**Comment by onedayfishsale** [comment] 2017-04-28 14:54
Same result in the GUI, detects the device and battery level, sync fails. Console output below.

$ ./run.sh 
------running openambit------
libambit WARNING: libambit_navigation_read(): Driver does not support navigation_waypoint_read
libambit WARNING: get_memory_maps(): Failed to read memory map key
asyncGet:  "https://uiservices.movescount.com/devices/Finch/69.2.17410?appkey=HpF9f1qV5qrDJ1hY1QK1diThyPsX10Mh4JvCw9xVQSglJNLdcwr3540zFyLzIC3e" 
asyncGet:  "https://uiservices.movescount.com/devices/Finch/69.2.17410?appkey=HpF9f1qV5qrDJ1hY1QK1diThyPsX10Mh4JvCw9xVQSglJNLdcwr3540zFyLzIC3e"

**Comment by landas** [comment] 2017-04-28 15:03
@onedayfishsale is it possible for you to send me an usb.log dump while you try with my openambit version?

**Comment by onedayfishsale** [comment] 2017-04-28 15:11
@landas Yep, sent it to you directly.

**Comment by jeremars** [comment] 2017-04-30 09:46
Thanks for your great work on openambit project. I'm newbee here. I recently have a sync problem with my Ambit3 Peak with moveslink mobile app : my move has been mark as sync on device but not really sync in movescount, so it's actually impossible for me to re-sync my move (it's was my first ultra trail, 105km)...
That's why I started to try openambit project on ubuntu. 
Actually my Ambit3 is  detected, but sync failed. 
I just have an USB pcap file of diagnostic suunto logs but impossible for me to extract data file or use wireshark dissector...
Do you know what is the original type of diagnostic logs file format and what tool can I use to rebuilt it ?
I can send you the dump file if it will be useful for the project.
Thank you for your help !

**Comment by landas** [comment] 2017-04-30 10:44
@jeremars: @onedayfishsale and I might have something that will work on newest firmware next week. It will not be perfect, but I think it will be able to sync logs (without heartrate) and upload to movescount.

**Comment by marguslt** [comment] 2017-04-30 18:16
@jeremars , Movescount mobile apps are keeping old _binlog*.bin_ and _*.json_ files. If you are able to get that json for your Move from phone, you can use curl to post it to Movescount manually. Looks something like:
`curl -vX POST "https://uiservices.movescount.com/moves/?appkey=<validAppKey>&userkey=<validUserKey>&email=movescount_user%40mail.kom" -d @2017-04-15T18_37_12.json -H "Content-Type: application/json" -H "User-Agent: Komposti/2.4.89 (Windows=Windows_7_Enterprise_Service_Pack_1) ArREST/1.0 Komposti/2.4.89 (Windows=Windows_7_Enterprise_Service_Pack_1) ArREST/1.0"` 

You can find appkey from Openambit sources (or from few posts above :) ),  userkey can be found from openambit settings file or from Moveslink2 _settings.xml_, 2017-04-15T18_37_12.json file is from phone app storage and email is the same you are logging in to Movescount. 

In case of un-rooted Android you can make app backup with `adb backup -nosystem com.suunto.movescount.android`  (developer options and usb debugging enabled in phone, adb for Ubuntu comes from android-tools-adb package ). For unpacking adb backup file there's  https://github.com/nelenkov/android-backup-extractor . For rooted phone you should have no issues accessing com.suunto.movescount.android/f/ with your favorite file manager. I'm assuming Movescount on IPhone handles files in similar way and there are probably some ways to get app backups.

If Movescount thinks that your Move was already uploaded, you need to adjust Duration field in json, it's in seconds and just adding +1 does the trick.

**Comment by jeremars** [comment] 2017-05-01 18:47
@marguslt Thank you for your detailled tips for recovering my move. I succeded to make an app backup, extract it but I don't find my move. I think it's because when I try to sync it at first time, app crashed and I must removed / re-install it for retry sync.
So I also try to find the diagnostic logs who are sent to suunto but I don't see the generated zip file in cache dir :
```
[2017-Apr-30 09:39:58 +0200] [INFO] makeLogZip() zip is named /storage/emulated/0/Android/data/com.suunto.movescount.android/cache/suunto.t03Lnd.zip
[2017-Apr-30 09:39:58 +0200] [INFO] Arrest: POST file /storage/emulated/0/Android/data/com.suunto.movescount.android/cache/suunto.t03Lnd.zip using URL https://juche-prod.movescount.com/juche-prod/FileUpload?appname=com.suunto.movescount.android
```
Do you know how I can get this generated file, on windows or android app ?
I called the Suunto support last week, they told me to do this for sending them the device data to recover my move. But no reply since...

Thank you for your help ! 👍

**Comment by marguslt** [comment] 2017-05-02 09:45
@jeremars , sorry, can't help you with diagnostic logs. Was makeLogZip() triggered somehow from Suunto?
There have been some reports in the past about Suunto support recovering Moves over TeamViewer that were lost  due mobile app - http://forums.watchuseek.com/f233/ambit3-move-not-synced-movescount-2114738-post23243082.html#post23243082  . Not sure if they have changed that policy or not. 

But if you have manually erased Movescount app data, I'm afraid there is no way to recover your activity from phone.  But just to be clear, the Move you are looking for is not in _apps/com.suunto.movescount.android/f/YourAmbit3SerialNumber/moves_ ?

If, by a chance, your ultra is still somehow listed in Android app, there's also _apps/com.suunto.movescount.android/db/movescount.db_  , an sqlite database that includes offline versions of all those moves listed in the app.  _moves_ table in _movescount.db_  includes _move_samples_ and _move_track_ fields, both are base64 encoded gzips of json arrays.  Data structure & content is different than in json that is sent to Movescount, but it should be possible to craft valid Movescount json or a GPX from that data. 

I'd also hold back with filling Ambit with more activity for now, just to give @landas work (and/or Suunto support) a chance.

**Comment by landas** [comment] 2017-05-02 15:03
@onedayfishsale and I have created an version that should be working at least with the latest firmware 2.4.1, and it seems like all his 40 logs on the ambit3 is extracted correctly.

We would be happy if more people could test the code with Ambit3 (any firmware) before we merge it to the openambit repository.

**You can download the code from:** https://github.com/landas/openambit/tree/ambit3new

If you choose to clone with git, please remember to `git checkout ambit3new` before compiling.

Compile with the following build options options for debugging data:
-DCMAKE_BUILD_TYPE=Debug -DDEBUG_PRINT_INFO=1

If your sync fail. please mail the console.log + usb.log to landas@gmail.com

For Usb-log you can use Wireshark or tcpdump (https://github.com/openambitproject/openambit/issues/54#issuecomment-296797463)

See https://github.com/openambitproject/openambit/blob/master/README.rst for information on how to build/compile.

**Comment by Idiotein** [comment] 2017-05-02 17:39
Whoa! Nice work @landas, my Ambit3 Peak with latest firmware syncs just fine with your code (57 logs), and I even managed to retrieve a move that Moveslink wouldn't sync and successfully upload it to Movescount. All of this while using my favourite OS, thanks a lot!
I checked the values and all seems fine, heart rate, temp, altitude, everything is there and correct. Only very minor glitch is that minimum heart rate value is always zero, but max and average are good.
Built you git  branch on Debian Stretch/Sid amd64.
Bravo.

**Comment by landas** [comment] 2017-05-02 18:41
@Idiotein @onedayfishsale, I'm not sure if the min hr value is a ambit3 specific problem.

I will test with my Ambit2 some time this week.

You could try to debug it with the dgb (line numbers are with the latest landas/openambit/ambit3new):
```
$ gdb /path/to/openambit
(gdb) set follow-fork-mode child
(gdb) b device_driver_ambit3.c:663
(gdb) b logstore.cpp:1490
(gdb) run
```

After you have started `gdb` use `<ctrl>+x <ctrl>+a` for a better view of source code. (will not show before you `run`.

**Comment by onedayfishsale** [comment] 2017-05-02 21:30
For what it's worth, I'm getting a zero out of pmem20.c:469 every time for the activities on my Ambit3.

`log_header->heartrate_min = read8inc(data, &offset);`

I'm working on fishing around in memory for the correct values, which I have from uploads via Moveslink2.

**Comment by landas** [comment] 2017-05-02 23:24
I have committed a hr min fix from @onedayfishsale to  https://github.com/landas/openambit/tree/ambit3new and #146 ,

We are not sure if this fix is compatible with older firmware versions for the hr min value.

**Comment by genexxa** [comment] 2017-05-09 17:33
I'm not very familiar with Linux.  I have Ubuntu on my laptop and trying to run the program and I'm totally lost.  I have read the documentation and nothing is working.  What would be the easiest way to run the program?

Thanks

**Closed** 2017-05-09 18:08 UTC
Labels: enhancement, libambit

**Comment by landas** [comment] 2017-05-09 18:24
@genexxa it depends. If you need ambit3 support with newest firmware, you must clone/download this github repository, and build it your self at the moment.

I need more information for one of us to help you. Is the problem cloning/downloading the source code, building, or running the executable you have built?

Any error message in the console?

**Comment by genexxa** [comment] 2017-05-10 19:28
Yes I'm trying to run it for an Ambit3 with the latest firmware.  I have tried to ''build'' it with command ./build.sh -DCMAKE_BUILD_TYPE=Debug but I get a load of error!!

**Comment by landas** [comment] 2017-05-10 21:20
@genexxa without error messages it is hard to say. You might be missing some packages?

Try installing the following packages:
`sudo apt-get install build-essential libqjson-dev zlib1g-dev libudev-dev libusb-1.0-0 cmake libudev1 libqt4-dev`

**Comment by genexxa** [comment] 2017-05-10 23:37
@landas Thanks the build phase looks fine now but I get a permission error when I try to run the application

anonymous@L300:~/Desktop/openambit-ambit3new$ sudo ./run.sh
------running openambit------
./run.sh: 23: ./run.sh: ./openambit-build/openambit: Permission denied

Thanks for your help!!

**Comment by landas** [comment] 2017-05-11 00:01
@genexxa on my Ubuntu I can not run the program as root with sudo. (But I get different error)

You could try this:
1) `sudo cp  ./src/libambit/libambit.rules /etc/udev/rules.d/`
2) `sudo udevadm control --reload-rules && udevadm trigger` or a reboot
3) Try to `./run.sh` without sudo.

**Comment by genexxa** [comment] 2017-05-11 01:31
Same error

**Comment by landas** [comment] 2017-05-11 11:03
@genexxa I could replicate this error message when I did not have file permission to the ./openambit-build/openambit

If you are not familiar with file permissions in Ubuntu `chmod` `chown`, you could try to delete the openambit folder, and clone, build and run again with your normal user.

**Comment by genexxa** [comment] 2017-05-11 13:43
@landas Getting there my friend.  The application is now running trough a VM on VmWare Workstation, but I get the error ''permission denied'' when I hit the refresh button.  Here's a screenshot of the error.

![permissiond](https://cloud.githubusercontent.com/assets/28572709/25952151/d0828706-362d-11e7-9d8e-b57f8a9f8180.jpg)

**Comment by landas** [comment] 2017-05-11 14:31
@genexxa I don't know why you get permission denied.
The `/etc/udev/rules.d/libambit.rules` file should be fixing this.
Can you check if your ambit type is listed there?

You can have a look here too:
https://askubuntu.com/questions/15570/configure-udev-to-change-permissions-on-usb-hid-device

**Comment by genexxa** [comment] 2017-05-11 14:34
@landas It's working!! I did a reboot and everything looks fine.  It's currently reading the content of the watch.

Thank you so much for your help!! Appreciated!!

**Comment by onedayfishsale** [comment] 2017-05-11 14:40
@genexxa If you have heart rate data with your activities, I'd be interested to hear if it uploads accurately, especially the "Min HR" fields.

**Comment by genexxa** [comment] 2017-05-11 14:51
@onedayfishsale Ok from openambit the Min HR field looks fine.  Now I'm trying to export one specific log to import it to Movescount.

**Comment by onedayfishsale** [comment] 2017-05-11 15:03
@genexxa Be sure to enable uploading in Openambit. Instructions here: https://github.com/openambitproject/openambit/issues/96#issuecomment-94269627

**Comment by genexxa** [comment] 2017-05-11 15:17
@onedayfishsale Thanks!! Done!  Hr value are perfect!

Thank you so much guys!

**Comment by onedayfishsale** [comment] 2017-05-11 15:20
@genexxa Thank you for testing. You're on firmware 2.4.1?

**Comment by genexxa** [comment] 2017-05-11 15:21
@onedayfishsale Yep

**Comment by Clight75** [comment] 2017-06-01 23:29
@landas I get exactly the same error ''permission denied'' in application when I connect my Ambit3 Peak and hit the refresh button as ganexxa in his post with screenshot. I tried to check the /etc/udev/rules.d/libambit.rules file, but the file does not exist in this location. I'm running Debian and Openambit 0.4 downloaded from this link: https://github.com/landas/openambit/tree/ambit3new . Can you help and advise how to fix it?

**Comment by Idiotein** [comment] 2017-06-02 08:25
Hi @Clight75,

at this point I would recommend building the main tree, Ambit3 related changes have been merged in openambit-master version 0.4.
You will find the udev rule file in src/libambit/libambit.rules (that's in the source folder where you have built openambit) , you need to copy it to /etc/udev/rules.d/ or wherever the udev rules are stored on your distribution.
To activate the rule you can try 
`sudo udevadm control --reload-rules && sudo udevadm trigger`

or reboot the system.

Hope this helps you.

**Comment by Clight75** [comment] 2017-06-03 09:46
Hi @Idiotein,
many thnaks for your help, it worked for me, I can download records from my Ambit3 now:)

**Comment by Malkavian81** [comment] 2017-06-27 10:37
Hi @Clight75 ,
which Linux do You use?
Can You download already downloaded moves from Your Suunto or only a new ones ?

**Comment by Clight75** [comment] 2017-06-27 18:02
Hi @Malkavian81,
I'm using Debian 9  - unstable version, on date when I was trying to get Openambit to work was not stable one available Final Debian 9 Stretch was released on 17th June, but I haven't updated my system yet). 
With first connection Openambit downloaded all moves from watches (even those which were already synchronized earlier via Windowss PC Moveslink application), then with next connections it downloads only new moves as those older are already kept in Openmabit list.

**Comment by nabadvin** [comment] 2017-08-21 07:45
Hi there!
I have successfully built the tree and it's running fine on Ubuntu 16.04 with my Ambit3 Run, thanks a lot!
But I noticed that the routes that I manually create in movescount map don't get downloaded to the watch (to be used with the function "run a route"). Is this the expected behaviour, or they should be synced?
Thanks and regards!

**Comment by VTiTux** [comment] 2018-07-29 14:09
Thank you very much, Svenstorp and all contributors for your work.
Moveslink on Windows and Movescount on Android failed to synchronise my last big move. It's my personnal record of this year, so, this move is very important for me.
And OpenAmbit 4 succeeded to upload it!
Great!

Why this big release (0.4) isn't available on the OpenAmbit web page?

**Comment by mbernasocchi** [comment] 2018-07-30 09:15
@VTiTux great to hear!
I updated the downloads section on openambit.org. The main page needs to be updated by @svenstorp. I already emailed him
cheers
